#!/usr/bin/env python3
"""Collect rope manipulation trajectories into an LE-WM-style HDF5 dataset."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

os.environ.setdefault("MUJOCO_GL", "egl")
os.environ.setdefault("PYOPENGL_PLATFORM", os.environ["MUJOCO_GL"])
os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import h5py
import imageio.v2 as imageio
import mujoco
import numpy as np
from tqdm.auto import tqdm

from rope.shared.lab_env import (
    LabEnv,
    RANDOM_CUBIC_SPLINE_MODE,
    RANDOM_WAYPOINT_MODE,
    RandomWaypointPolicy,
    RandomSplinePolicy,
    TaskBounds,
    WS_EDGE_SAMPLE_MODE,
    WorkspaceEdgeSamplePolicy,
)


DEFAULT_OUTDIR = "rope/data/test_2_data_noshadow"
DEFAULT_OUTPUT_NAME = "rope_random_cubic_spline.h5"
DEFAULT_CAMERA = "video_cam"
DEFAULT_MODE = RANDOM_CUBIC_SPLINE_MODE
ACTION_DIM = 3
DISABLE_SHADOW=True

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument("--output-name", default=DEFAULT_OUTPUT_NAME)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument(
        "--target-transitions",
        type=int,
        default=None,
        help="Collect variable-length trajectories until this many action transitions are stored.",
    )
    parser.add_argument(
        "--num-trajectories",
        type=int,
        default=3000,
        help="Fallback collection target when --target-transitions is omitted.",
    )
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--max-episode-steps", type=int, default=100)
    parser.add_argument("--min-steps", type=int, default=3)
    parser.add_argument("--width", type=int, default=224)
    parser.add_argument("--height", type=int, default=224)
    parser.add_argument("--quality", type=int, default=8)
    parser.add_argument("--compression", choices=("none", "lzf", "gzip"), default="lzf")
    parser.add_argument("--camera", default=DEFAULT_CAMERA)
    parser.add_argument(
        "--save-mp4",
        action="store_true",
        default=False,
        help="Write per-trajectory MP4 files alongside the HDF5 dataset.",
    )
    parser.add_argument(
        "--disable-shadows",
        action="store_true",
        default=DISABLE_SHADOW,
        help="Disable shadow rendering for frames generated by this script only.",
    )
    parser.add_argument(
        "--mode",
        default=DEFAULT_MODE,
        choices=(RANDOM_CUBIC_SPLINE_MODE, RANDOM_WAYPOINT_MODE, WS_EDGE_SAMPLE_MODE),
        help="Task-space trajectory generator.",
    )
    parser.add_argument(
        "--control-decimation",
        type=int,
        default=25,
        help="Number of MuJoCo substeps per recorded control/action step.",
    )
    parser.add_argument(
        "--segment-duration",
        type=float,
        default=4.0,
        help="Duration of each policy segment in seconds.",
    )
    parser.add_argument(
        "--num-waypoints",
        type=int,
        default=6,
        help="Number of waypoints for RANDOM_WAYPOINT mode.",
    )
    parser.add_argument(
        "--midpoint-inflation-scale",
        type=float,
        default=0.08,
        help="Relative box inflation used only for the cubic spline midpoint sample.",
    )
    parser.add_argument(
        "--goal-tolerance",
        type=float,
        default=1e-4,
        help="Terminate an episode once the task target is within this L2 distance of the final goal.",
    )
    return parser.parse_args()


def create_resizable_dataset(
    h5: h5py.File,
    name: str,
    shape_tail: tuple[int, ...],
    dtype: np.dtype | type,
    *,
    compression: str | None = None,
    chunks: tuple[int, ...] | bool | None = True,
) -> h5py.Dataset:
    return h5.create_dataset(
        name,
        shape=(0, *shape_tail),
        maxshape=(None, *shape_tail),
        dtype=dtype,
        compression=compression,
        chunks=chunks,
    )


def append_rows(dataset: h5py.Dataset, values: np.ndarray) -> tuple[int, int]:
    start = int(dataset.shape[0])
    end = start + int(values.shape[0])
    dataset.resize((end, *dataset.shape[1:]))
    dataset[start:end] = values
    return start, end


def valid_training_windows(ep_len: np.ndarray, *, history_size: int = 3, num_preds: int = 1, frameskip: int = 1) -> int:
    num_steps = history_size + num_preds
    required_last_frame_offset = (num_steps - 1) * frameskip
    required_action_end_offset = history_size * frameskip
    required_offset = max(required_last_frame_offset, required_action_end_offset)
    return int(np.maximum(ep_len - 1 - required_offset + 1, 0).sum())


def should_continue(args: argparse.Namespace, num_trajectories: int, total_transitions: int) -> bool:
    if args.target_transitions is not None:
        return total_transitions < args.target_transitions
    return num_trajectories < args.num_trajectories


def make_policy(
    args: argparse.Namespace,
    bounds: TaskBounds,
    *,
    seed: int,
) -> RandomWaypointPolicy | RandomSplinePolicy | WorkspaceEdgeSamplePolicy:
    if args.mode == RANDOM_CUBIC_SPLINE_MODE:
        return RandomSplinePolicy(
            bounds,
            seed=seed,
            segment_duration=args.segment_duration,
            midpoint_inflation_scale=args.midpoint_inflation_scale,
        )
    if args.mode == RANDOM_WAYPOINT_MODE:
        return RandomWaypointPolicy(
            bounds=bounds,
            seed=seed,
            segment_duration=args.segment_duration,
            num_waypoints=args.num_waypoints,
        )
    if args.mode == WS_EDGE_SAMPLE_MODE:
        return WorkspaceEdgeSamplePolicy(bounds=bounds, segment_duration=args.segment_duration)
    raise ValueError(f"Unsupported mode: {args.mode}")


def current_task_target(env: LabEnv) -> np.ndarray:
    return env.task_controller.desired_state.as_array().astype(np.float32)


def policy_duration(policy: RandomWaypointPolicy | RandomSplinePolicy | WorkspaceEdgeSamplePolicy) -> float:
    if isinstance(policy, RandomWaypointPolicy):
        return float((len(policy._waypoints) - 1) * policy.segment_duration)
    if isinstance(policy, RandomSplinePolicy):
        return float(policy.segment_duration)
    if isinstance(policy, WorkspaceEdgeSamplePolicy):
        return float(policy.segment_duration)
    raise TypeError(f"Unsupported policy type: {type(policy)!r}")


def policy_goal_state(policy: RandomWaypointPolicy | RandomSplinePolicy | WorkspaceEdgeSamplePolicy) -> np.ndarray:
    if isinstance(policy, RandomWaypointPolicy):
        return np.asarray(policy._waypoints[-1], dtype=np.float32)
    if isinstance(policy, RandomSplinePolicy):
        return np.asarray(policy.bounds.clip(policy._control_points[-1]).as_array(), dtype=np.float32)
    if isinstance(policy, WorkspaceEdgeSamplePolicy):
        start, end = policy._segments[0]
        del start
        return np.asarray(policy.bounds.clip(end).as_array(), dtype=np.float32)
    raise TypeError(f"Unsupported policy type: {type(policy)!r}")


def extract_step_info(env: LabEnv, *, elapsed_time: float) -> dict[str, np.ndarray]:
    left_pos = env.data.site_xpos[env.arm1_site_id].copy()
    right_pos = env.data.site_xpos[env.arm2_site_id].copy()
    rope_length = env.data.ten_length.copy()
    target = current_task_target(env)
    qpos = env.data.qpos.copy().astype(np.float32)
    qvel = env.data.qvel.copy().astype(np.float32)
    control = env.data.ctrl.copy().astype(np.float32)
    left_pos = left_pos.astype(np.float32)
    right_pos = right_pos.astype(np.float32)
    rope_length = rope_length.astype(np.float32)
    observation = np.concatenate(
        [
            target,
            qpos,
            qvel,
            control,
            left_pos,
            right_pos,
            rope_length,
        ],
        axis=0,
    ).astype(np.float32)
    return {
        "observation": observation,
        "task_target": target,
        "qpos": qpos,
        "qvel": qvel,
        "control": control,
        "left_attachment_pos": left_pos,
        "right_attachment_pos": right_pos,
        "rope_length": rope_length,
        "time": np.asarray([elapsed_time], dtype=np.float32),
    }


def render_rgb_frame(
    renderer: mujoco.Renderer,
    env: LabEnv,
    camera_id: int,
    *,
    disable_shadows: bool = False,
) -> np.ndarray:
    renderer.update_scene(env.data, camera=camera_id)
    if disable_shadows:
        renderer.scene.flags[mujoco.mjtRndFlag.mjRND_SHADOW] = 0
    return np.asarray(renderer.render(), dtype=np.uint8).copy()


def collect_trajectory(
    *,
    env: LabEnv,
    renderer: mujoco.Renderer,
    camera_id: int,
    trajectory_seed: int,
    max_episode_steps: int,
    control_decimation: int,
    control_timestep: float,
    args: argparse.Namespace,
) -> tuple[dict[str, np.ndarray], bool, bool]:
    policy = make_policy(args, env.task_bounds, seed=trajectory_seed)
    initial_target = policy.sample(0.0)
    final_goal = policy_goal_state(policy)
    total_duration = policy_duration(policy)
    env.reset(initial_target)

    step_info = extract_step_info(env, elapsed_time=0.0)
    observations = [step_info["observation"]]
    frames = [render_rgb_frame(renderer, env, camera_id, disable_shadows=args.disable_shadows)]
    actions: list[np.ndarray] = []
    task_target = [step_info["task_target"]]
    qpos = [step_info["qpos"]]
    qvel = [step_info["qvel"]]
    control = [step_info["control"]]
    left_attachment_pos = [step_info["left_attachment_pos"]]
    right_attachment_pos = [step_info["right_attachment_pos"]]
    rope_length = [step_info["rope_length"]]
    time = [step_info["time"]]

    current_target = current_task_target(env).astype(np.float64)
    terminated = False
    truncated = False
    for step_idx in range(max_episode_steps):
        sample_time = min((step_idx + 1) * control_timestep, total_duration)
        desired = policy.sample(sample_time).as_array()
        requested_delta = desired - current_target
        env.apply_task_delta(requested_delta)
        applied_target = current_task_target(env).astype(np.float64)
        applied_delta = (applied_target - current_target).astype(np.float32)
        env.step(control_decimation)

        actions.append(applied_delta)
        current_target = applied_target
        step_info = extract_step_info(env, elapsed_time=sample_time)
        observations.append(step_info["observation"])
        frames.append(render_rgb_frame(renderer, env, camera_id, disable_shadows=args.disable_shadows))
        task_target.append(step_info["task_target"])
        qpos.append(step_info["qpos"])
        qvel.append(step_info["qvel"])
        control.append(step_info["control"])
        left_attachment_pos.append(step_info["left_attachment_pos"])
        right_attachment_pos.append(step_info["right_attachment_pos"])
        rope_length.append(step_info["rope_length"])
        time.append(step_info["time"])

        if np.linalg.norm(step_info["task_target"] - final_goal) <= args.goal_tolerance:
            terminated = True
            break

    if not terminated:
        truncated = True

    data = {
        "observation": np.stack(observations, axis=0),
        "pixels": np.stack(frames, axis=0),
        "action": np.stack(actions, axis=0) if actions else np.zeros((0, ACTION_DIM), dtype=np.float32),
        "task_target": np.stack(task_target, axis=0),
        "qpos": np.stack(qpos, axis=0),
        "qvel": np.stack(qvel, axis=0),
        "control": np.stack(control, axis=0),
        "left_attachment_pos": np.stack(left_attachment_pos, axis=0),
        "right_attachment_pos": np.stack(right_attachment_pos, axis=0),
        "rope_length": np.stack(rope_length, axis=0),
        "time": np.stack(time, axis=0),
    }
    return data, terminated, truncated


def main() -> None:
    args = parse_args()
    if args.target_transitions is not None and args.target_transitions < 1:
        raise ValueError("--target-transitions must be positive when provided.")
    if args.num_trajectories < 1:
        raise ValueError("--num-trajectories must be positive.")
    if args.max_episode_steps < 1:
        raise ValueError("--max-episode-steps must be positive.")
    if args.min_steps < 1:
        raise ValueError("--min-steps must be positive.")
    if args.control_decimation < 1:
        raise ValueError("--control-decimation must be positive.")
    if args.segment_duration <= 0.0:
        raise ValueError("--segment-duration must be positive.")
    if args.num_waypoints < 2:
        raise ValueError("--num-waypoints must be at least 2.")
    if args.midpoint_inflation_scale < 0.0:
        raise ValueError("--midpoint-inflation-scale cannot be negative.")
    if args.goal_tolerance < 0.0:
        raise ValueError("--goal-tolerance cannot be negative.")

    outdir = args.outdir.expanduser().resolve()
    video_dir = outdir / "videos"
    output_path = outdir / args.output_name
    outdir.mkdir(parents=True, exist_ok=True)
    video_dir.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and not args.overwrite:
        raise FileExistsError(f"Output file already exists: {output_path}. Pass --overwrite to replace it.")
    if output_path.exists():
        output_path.unlink()

    compression = None if args.compression == "none" else args.compression
    rewards: list[float] = []
    step_counts: list[int] = []
    terminated_flags: list[bool] = []
    truncated_flags: list[bool] = []
    skipped_short = 0
    seed_offset = 0

    env = LabEnv()
    control_timestep = float(env.model.opt.timestep) * args.control_decimation
    control_freq_hz = 1.0 / control_timestep
    camera_id = env.model.camera(args.camera).id

    with mujoco.Renderer(env.model, height=args.height, width=args.width) as renderer:
        env.reset()
        sample_step_info = extract_step_info(env, elapsed_time=0.0)
        sample_frame = render_rgb_frame(renderer, env, camera_id, disable_shadows=args.disable_shadows)
        obs_dim = int(sample_step_info["observation"].shape[0])
        qpos_dim = int(sample_step_info["qpos"].shape[0])
        qvel_dim = int(sample_step_info["qvel"].shape[0])
        control_dim = int(sample_step_info["control"].shape[0])

        with h5py.File(output_path, "w") as h5:
            h5.attrs["format"] = "stable_worldmodel_hdf5"
            h5.attrs["source"] = "rope/data/rope_data_gen.py"
            h5.attrs["seed"] = args.seed
            h5.attrs["video_dir"] = str(video_dir)
            h5.attrs["video_resolution"] = json.dumps([args.height, args.width])
            h5.attrs["save_mp4"] = args.save_mp4
            h5.attrs["camera"] = args.camera
            h5.attrs["disable_shadows"] = args.disable_shadows
            h5.attrs["mode"] = args.mode
            h5.attrs["video_fps"] = control_freq_hz
            h5.attrs["physics_timestep"] = float(env.model.opt.timestep)
            h5.attrs["control_timestep"] = control_timestep
            h5.attrs["control_decimation"] = args.control_decimation
            h5.attrs["max_episode_steps"] = args.max_episode_steps
            h5.attrs["segment_duration"] = args.segment_duration
            h5.attrs["num_waypoints"] = args.num_waypoints
            h5.attrs["goal_tolerance"] = args.goal_tolerance
            h5.attrs["observation_dim"] = obs_dim
            h5.attrs["action_dim"] = ACTION_DIM
            h5.attrs["qpos_dim"] = qpos_dim
            h5.attrs["qvel_dim"] = qvel_dim
            h5.attrs["control_dim"] = control_dim
            h5.attrs["task_bounds"] = json.dumps(
                {
                    "reach": list(env.task_bounds.reach),
                    "height": list(env.task_bounds.height),
                    "width": list(env.task_bounds.width),
                }
            )
            h5.attrs["nominal_task_state"] = json.dumps(env.nominal_state.as_array().tolist())

            ep_len_ds = create_resizable_dataset(h5, "ep_len", (), np.int64, chunks=True)
            ep_offset_ds = create_resizable_dataset(h5, "ep_offset", (), np.int64, chunks=True)
            reward_ds = create_resizable_dataset(h5, "reward", (), np.float32, chunks=True)
            seed_ds = create_resizable_dataset(h5, "episode_seed", (), np.int64, chunks=True)
            terminated_ds = create_resizable_dataset(h5, "terminated", (), np.bool_, chunks=True)
            truncated_ds = create_resizable_dataset(h5, "truncated", (), np.bool_, chunks=True)
            pixels_ds = create_resizable_dataset(
                h5,
                "pixels",
                sample_frame.shape,
                np.uint8,
                compression=compression,
                chunks=(1, *sample_frame.shape),
            )
            action_ds = create_resizable_dataset(h5, "action", (ACTION_DIM,), np.float32, chunks=True)
            obs_ds = create_resizable_dataset(h5, "observation", (obs_dim,), np.float32, chunks=True)
            task_target_ds = create_resizable_dataset(h5, "task_target", (3,), np.float32, chunks=True)
            qpos_ds = create_resizable_dataset(h5, "qpos", (qpos_dim,), np.float32, chunks=True)
            qvel_ds = create_resizable_dataset(h5, "qvel", (qvel_dim,), np.float32, chunks=True)
            control_ds = create_resizable_dataset(h5, "control", (control_dim,), np.float32, chunks=True)
            left_attachment_pos_ds = create_resizable_dataset(h5, "left_attachment_pos", (3,), np.float32, chunks=True)
            right_attachment_pos_ds = create_resizable_dataset(h5, "right_attachment_pos", (3,), np.float32, chunks=True)
            rope_length_ds = create_resizable_dataset(h5, "rope_length", (1,), np.float32, chunks=True)
            time_ds = create_resizable_dataset(h5, "time", (1,), np.float32, chunks=True)
            episode_idx_ds = create_resizable_dataset(h5, "episode_idx", (), np.int64, chunks=True)
            step_idx_ds = create_resizable_dataset(h5, "step_idx", (), np.int64, chunks=True)

            progress_total = args.target_transitions if args.target_transitions is not None else args.num_trajectories
            progress_desc = "Collecting transitions" if args.target_transitions is not None else "Collecting trajectories"
            progress_unit = "step" if args.target_transitions is not None else "traj"

            with tqdm(total=progress_total, desc=progress_desc, unit=progress_unit) as progress:
                while should_continue(args, len(step_counts), int(np.sum(step_counts, dtype=np.int64))):
                    trajectory_seed = args.seed + seed_offset
                    seed_offset += 1

                    trajectory, terminated, truncated = collect_trajectory(
                        env=env,
                        renderer=renderer,
                        camera_id=camera_id,
                        trajectory_seed=trajectory_seed,
                        max_episode_steps=args.max_episode_steps,
                        control_decimation=args.control_decimation,
                        control_timestep=control_timestep,
                        args=args,
                    )

                    num_actions = int(trajectory["action"].shape[0])
                    if num_actions < args.min_steps:
                        skipped_short += 1
                        continue

                    episode_idx = len(step_counts)
                    if args.save_mp4:
                        video_path = video_dir / f"trajectory_{episode_idx:07d}.mp4"
                        imageio.mimwrite(
                            video_path,
                            trajectory["pixels"],
                            fps=control_freq_hz,
                            quality=args.quality,
                            macro_block_size=1,
                        )

                    padded_actions = np.empty((trajectory["observation"].shape[0], ACTION_DIM), dtype=np.float32)
                    padded_actions[:-1] = trajectory["action"]
                    padded_actions[-1] = np.nan

                    offset, _ = append_rows(pixels_ds, trajectory["pixels"])
                    append_rows(action_ds, padded_actions)
                    append_rows(obs_ds, trajectory["observation"])
                    append_rows(task_target_ds, trajectory["task_target"])
                    append_rows(qpos_ds, trajectory["qpos"])
                    append_rows(qvel_ds, trajectory["qvel"])
                    append_rows(control_ds, trajectory["control"])
                    append_rows(left_attachment_pos_ds, trajectory["left_attachment_pos"])
                    append_rows(right_attachment_pos_ds, trajectory["right_attachment_pos"])
                    append_rows(rope_length_ds, trajectory["rope_length"])
                    append_rows(time_ds, trajectory["time"])
                    append_rows(episode_idx_ds, np.full((trajectory["observation"].shape[0],), episode_idx, dtype=np.int64))
                    append_rows(step_idx_ds, np.arange(trajectory["observation"].shape[0], dtype=np.int64))
                    append_rows(ep_len_ds, np.asarray([trajectory["observation"].shape[0]], dtype=np.int64))
                    append_rows(ep_offset_ds, np.asarray([offset], dtype=np.int64))
                    append_rows(reward_ds, np.asarray([0.0], dtype=np.float32))
                    append_rows(seed_ds, np.asarray([trajectory_seed], dtype=np.int64))
                    append_rows(terminated_ds, np.asarray([terminated], dtype=np.bool_))
                    append_rows(truncated_ds, np.asarray([truncated], dtype=np.bool_))

                    rewards.append(0.0)
                    step_counts.append(num_actions)
                    terminated_flags.append(terminated)
                    truncated_flags.append(truncated)
                    progress.update(num_actions if args.target_transitions is not None else 1)
                    progress.set_postfix(
                        episodes=len(step_counts),
                        transitions=int(np.sum(step_counts, dtype=np.int64)),
                    )

            ep_len = np.asarray(ep_len_ds[:], dtype=np.int64)
            h5.attrs["num_episodes"] = len(step_counts)
            h5.attrs["total_frames"] = int(pixels_ds.shape[0])
            h5.attrs["total_transitions"] = int(np.sum(step_counts, dtype=np.int64))
            h5.attrs["skipped_short_episodes"] = skipped_short
            h5.attrs["mean_reward"] = float(np.mean(rewards)) if rewards else 0.0
            h5.attrs["mean_episode_steps"] = float(np.mean(step_counts)) if step_counts else 0.0
            h5.attrs["terminated_fraction"] = float(np.mean(terminated_flags)) if terminated_flags else 0.0
            h5.attrs["truncated_fraction"] = float(np.mean(truncated_flags)) if truncated_flags else 0.0
            h5.attrs["usable_train_windows_default"] = valid_training_windows(ep_len)

    summary = {
        "output_path": str(output_path),
        "video_dir": str(video_dir),
        "num_episodes": len(step_counts),
        "total_transitions": int(np.sum(step_counts, dtype=np.int64)),
        "mean_episode_steps": float(np.mean(step_counts)) if step_counts else 0.0,
        "control_timestep": control_timestep,
        "control_fps": control_freq_hz,
        "mode": args.mode,
    }
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
